import type {
  User,
  Advertiser,
  Partner,
  Program,
  Conversion,
  Payout,
  MediaInventory,
  AdvertiserDashboard,
  PartnerDashboard,
  AdminDashboard,
} from '@/types';

// Mock Users
export const mockUsers: User[] = [
  {
    id: 'user_1',
    name: 'Sarah Wijaya',
    email: 'sarah@tunaiku.com',
    role: 'advertiser',
    company_name: 'Tunaiku',
    created_at: '2024-01-15T08:00:00Z',
  },
  {
    id: 'user_2',
    name: 'Budi Santoso',
    email: 'budi@jakselnews.com',
    role: 'partner',
    company_name: 'JakselNews Media',
    created_at: '2024-02-20T10:00:00Z',
  },
  {
    id: 'user_3',
    name: 'Admin User',
    email: 'admin@cuanpintar.com',
    role: 'admin',
    created_at: '2024-01-01T00:00:00Z',
  },
];

// Mock Advertisers
export const mockAdvertisers: Advertiser[] = [
  {
    id: 'adv_1',
    user_id: 'user_1',
    company_name: 'Tunaiku',
    industry: 'Financial Services',
    website: 'https://tunaiku.com',
    status: 'active',
    total_spend: 125000000,
    active_programs: 3,
    created_at: '2024-01-15T08:00:00Z',
  },
  {
    id: 'adv_2',
    user_id: 'user_4',
    company_name: 'Prudential',
    industry: 'Insurance',
    website: 'https://prudential.co.id',
    status: 'active',
    total_spend: 89000000,
    active_programs: 2,
    created_at: '2024-01-20T09:00:00Z',
  },
  {
    id: 'adv_3',
    user_id: 'user_5',
    company_name: 'XL Axiata',
    industry: 'Telecommunications',
    website: 'https://xl.co.id',
    status: 'active',
    total_spend: 67000000,
    active_programs: 1,
    created_at: '2024-02-01T10:00:00Z',
  },
  {
    id: 'adv_4',
    user_id: 'user_6',
    company_name: 'Pegadaian',
    industry: 'Financial Services',
    website: 'https://pegadaian.co.id',
    status: 'active',
    total_spend: 45000000,
    active_programs: 2,
    created_at: '2024-02-10T11:00:00Z',
  },
  {
    id: 'adv_5',
    user_id: 'user_7',
    company_name: 'AstraPay',
    industry: 'Fintech',
    website: 'https://astrapay.com',
    status: 'active',
    total_spend: 38000000,
    active_programs: 1,
    created_at: '2024-02-15T12:00:00Z',
  },
  {
    id: 'adv_6',
    user_id: 'user_8',
    company_name: 'Bank Saqu',
    industry: 'Banking',
    website: 'https://banksaqu.com',
    status: 'active',
    total_spend: 52000000,
    active_programs: 2,
    created_at: '2024-02-20T13:00:00Z',
  },
  {
    id: 'adv_7',
    user_id: 'user_9',
    company_name: 'TMRW by UOB',
    industry: 'Banking',
    website: 'https://tmrw.com',
    status: 'active',
    total_spend: 31000000,
    active_programs: 1,
    created_at: '2024-03-01T14:00:00Z',
  },
  {
    id: 'adv_8',
    user_id: 'user_10',
    company_name: 'IKEA Indonesia',
    industry: 'Retail',
    website: 'https://ikea.co.id',
    status: 'active',
    total_spend: 28000000,
    active_programs: 1,
    created_at: '2024-03-05T15:00:00Z',
  },
  {
    id: 'adv_9',
    user_id: 'user_11',
    company_name: 'Pizza Hut Indonesia',
    industry: 'F&B',
    website: 'https://pizzahut.co.id',
    status: 'active',
    total_spend: 22000000,
    active_programs: 1,
    created_at: '2024-03-10T16:00:00Z',
  },
  {
    id: 'adv_10',
    user_id: 'user_12',
    company_name: 'Yamaha Indonesia',
    industry: 'Automotive',
    website: 'https://yamaha-motor.co.id',
    status: 'pending',
    total_spend: 0,
    active_programs: 0,
    created_at: '2024-03-15T17:00:00Z',
  },
];

// Mock Partners
export const mockPartners: Partner[] = [
  {
    id: 'part_1',
    user_id: 'user_2',
    partner_name: 'JakselNews Media Network',
    partner_type: 'media',
    niche: 'Lifestyle & Urban',
    location: 'Jakarta Selatan',
    audience_size: 2500000,
    quality_score: 92,
    fraud_risk: 'low',
    status: 'active',
    total_earnings: 18500000,
    total_paid: 14800000,
    pending_payout: 3700000,
    pending_conversions: 0,
    total_conversions: 370,
    valid_conversions: 333,
    rejected_conversions: 0,
    fraud_conversions: 0,
    fraud_rate: 0,
    conversion_rate: 0.02,
    avg_payout_per_conversion: 50000,
    created_at: '2024-02-20T10:00:00Z',
  },
  {
    id: 'part_2',
    user_id: 'user_13',
    partner_name: 'Finance Creator Jakarta',
    partner_type: 'creator',
    niche: 'Personal Finance',
    location: 'Jakarta',
    audience_size: 450000,
    quality_score: 88,
    fraud_risk: 'low',
    status: 'active',
    total_earnings: 12300000,
    total_paid: 9840000,
    pending_payout: 2460000,
    pending_conversions: 0,
    total_conversions: 246,
    valid_conversions: 221,
    rejected_conversions: 0,
    fraud_conversions: 0,
    fraud_rate: 0,
    conversion_rate: 0.02,
    avg_payout_per_conversion: 50000,
    created_at: '2024-02-25T11:00:00Z',
  },
  {
    id: 'part_3',
    user_id: 'user_14',
    partner_name: 'Local Media Bandung',
    partner_type: 'media',
    niche: 'Local News',
    location: 'Bandung',
    audience_size: 890000,
    quality_score: 85,
    fraud_risk: 'low',
    status: 'active',
    total_earnings: 7800000,
    total_paid: 6240000,
    pending_payout: 1560000,
    pending_conversions: 0,
    total_conversions: 156,
    valid_conversions: 140,
    rejected_conversions: 0,
    fraud_conversions: 0,
    fraud_rate: 0,
    conversion_rate: 0.02,
    avg_payout_per_conversion: 50000,
    created_at: '2024-03-01T12:00:00Z',
  },
  {
    id: 'part_4',
    user_id: 'user_15',
    partner_name: 'Parenting Community Indonesia',
    partner_type: 'community',
    niche: 'Parenting & Family',
    location: 'Nasional',
    audience_size: 1200000,
    quality_score: 90,
    fraud_risk: 'low',
    status: 'active',
    total_earnings: 9500000,
    total_paid: 7600000,
    pending_payout: 1900000,
    pending_conversions: 0,
    total_conversions: 190,
    valid_conversions: 171,
    rejected_conversions: 0,
    fraud_conversions: 0,
    fraud_rate: 0,
    conversion_rate: 0.02,
    avg_payout_per_conversion: 50000,
    created_at: '2024-03-05T13:00:00Z',
  },
  {
    id: 'part_5',
    user_id: 'user_16',
    partner_name: 'Campus Sales Team',
    partner_type: 'sales',
    niche: 'Student Acquisition',
    location: 'Jakarta',
    audience_size: 50000,
    quality_score: 78,
    fraud_risk: 'medium',
    status: 'active',
    total_earnings: 4200000,
    total_paid: 3360000,
    pending_payout: 840000,
    pending_conversions: 0,
    total_conversions: 84,
    valid_conversions: 75,
    rejected_conversions: 0,
    fraud_conversions: 0,
    fraud_rate: 0,
    conversion_rate: 0.02,
    avg_payout_per_conversion: 50000,
    created_at: '2024-03-10T14:00:00Z',
  },
  {
    id: 'part_6',
    user_id: 'user_17',
    partner_name: 'Affiliate Finance Partner',
    partner_type: 'affiliate',
    niche: 'Financial Products',
    location: 'Nasional',
    audience_size: 320000,
    quality_score: 82,
    fraud_risk: 'low',
    status: 'active',
    total_earnings: 15600000,
    total_paid: 12480000,
    pending_payout: 3120000,
    pending_conversions: 0,
    total_conversions: 312,
    valid_conversions: 280,
    rejected_conversions: 0,
    fraud_conversions: 0,
    fraud_rate: 0,
    conversion_rate: 0.02,
    avg_payout_per_conversion: 50000,
    created_at: '2024-03-15T15:00:00Z',
  },
  {
    id: 'part_7',
    user_id: 'user_18',
    partner_name: 'Mission User Network',
    partner_type: 'mission',
    niche: 'Rewards & Incentives',
    location: 'Nasional',
    audience_size: 150000,
    quality_score: 65,
    fraud_risk: 'high',
    status: 'active',
    total_earnings: 8900000,
    total_paid: 7120000,
    pending_payout: 1780000,
    pending_conversions: 0,
    total_conversions: 178,
    valid_conversions: 160,
    rejected_conversions: 0,
    fraud_conversions: 0,
    fraud_rate: 0,
    conversion_rate: 0.02,
    avg_payout_per_conversion: 50000,
    created_at: '2024-03-20T16:00:00Z',
  },
  {
    id: 'part_8',
    user_id: 'user_19',
    partner_name: 'Automotive Creator',
    partner_type: 'creator',
    niche: 'Motorcycle & Cars',
    location: 'Jakarta',
    audience_size: 680000,
    quality_score: 87,
    fraud_risk: 'low',
    status: 'active',
    total_earnings: 10200000,
    total_paid: 8160000,
    pending_payout: 2040000,
    pending_conversions: 0,
    total_conversions: 204,
    valid_conversions: 183,
    rejected_conversions: 0,
    fraud_conversions: 0,
    fraud_rate: 0,
    conversion_rate: 0.02,
    avg_payout_per_conversion: 50000,
    created_at: '2024-03-25T17:00:00Z',
  },
  {
    id: 'part_9',
    user_id: 'user_20',
    partner_name: 'Muslim Family Media',
    partner_type: 'media',
    niche: 'Islamic Content',
    location: 'Nasional',
    audience_size: 1800000,
    quality_score: 91,
    fraud_risk: 'low',
    status: 'active',
    total_earnings: 13400000,
    total_paid: 10720000,
    pending_payout: 2680000,
    pending_conversions: 0,
    total_conversions: 268,
    valid_conversions: 241,
    rejected_conversions: 0,
    fraud_conversions: 0,
    fraud_rate: 0,
    conversion_rate: 0.02,
    avg_payout_per_conversion: 50000,
    created_at: '2024-04-01T18:00:00Z',
  },
  {
    id: 'part_10',
    user_id: 'user_21',
    partner_name: 'Lifestyle Creator',
    partner_type: 'creator',
    niche: 'Lifestyle & Trends',
    location: 'Surabaya',
    audience_size: 380000,
    quality_score: 84,
    fraud_risk: 'low',
    status: 'pending',
    total_earnings: 0,
    total_paid: 0,
    pending_payout: 0,
    pending_conversions: 0,
    total_conversions: 0,
    valid_conversions: 0,
    rejected_conversions: 0,
    fraud_conversions: 0,
    fraud_rate: 0,
    conversion_rate: 0.02,
    avg_payout_per_conversion: 50000,
    created_at: '2024-04-05T19:00:00Z',
  },
];

// Mock Programs
export const mockPrograms: Program[] = [
  {
    id: 'prog_1',
    advertiser_id: 'adv_1',
    advertiser_name: 'Tunaiku',
    name: 'Tunaiku Download + Registration',
    brand_name: 'Tunaiku',
    industry: 'Financial Services',
    description: 'Acquire new Tunaiku app users through registration program targeting young professionals in Jakarta and Surabaya.',
    objectives: ['app_install', 'registration'],
    target_audience: {
      age: '21-35',
      gender: 'all',
      location: 'Jakarta, Surabaya, Bandung',
      interest: 'Personal Finance, Investment',
      device: 'Mobile',
      notes: 'Focus on first-time credit seekers',
    },
    budget: 50000000,
    payout_model: 'CPA',
    payout_amount: 25000,
    advertiser_price: 30000,
    partner_payout: 5000,
    platform_profit: 25000,
    total_advertiser_cost: 60000000,
    total_partner_payout: 10000000,
    total_platform_profit: 50000000,
    target_volume: 2000,
    status: 'active',
    channels: [
      { channel_type: 'media', allocated_budget: 20000000, estimated_volume: 800, quality_score: 88, fraud_risk: 'low' },
      { channel_type: 'creator', allocated_budget: 15000000, estimated_volume: 600, quality_score: 92, fraud_risk: 'low' },
      { channel_type: 'affiliate', allocated_budget: 10000000, estimated_volume: 400, quality_score: 82, fraud_risk: 'low' },
      { channel_type: 'sales', allocated_budget: 3000000, estimated_volume: 120, quality_score: 78, fraud_risk: 'medium' },
      { channel_type: 'mission', allocated_budget: 2000000, estimated_volume: 80, quality_score: 65, fraud_risk: 'high' },
    ],
    start_date: '2024-04-01',
    end_date: '2024-06-30',
    created_at: '2024-03-25T10:00:00Z',
  },
  {
    id: 'prog_2',
    advertiser_id: 'adv_2',
    advertiser_name: 'Prudential',
    name: 'PRULady Lead Form',
    brand_name: 'Prudential',
    industry: 'Insurance',
    description: 'Generate qualified insurance leads from female professionals interested in women-focused insurance products.',
    objectives: ['lead_form'],
    target_audience: {
      age: '25-45',
      gender: 'female',
      location: 'Nasional',
      interest: 'Insurance, Family Protection',
      device: 'Mobile, Desktop',
      notes: 'Target working mothers and professionals',
    },
    budget: 40000000,
    payout_model: 'CPL',
    payout_amount: 50000,
    advertiser_price: 50000,
    partner_payout: 15000,
    platform_profit: 35000,
    total_advertiser_cost: 40000000,
    total_partner_payout: 12000000,
    total_platform_profit: 28000000,
    target_volume: 800,
    status: 'active',
    channels: [
      { channel_type: 'media', allocated_budget: 18000000, estimated_volume: 360, quality_score: 90, fraud_risk: 'low' },
      { channel_type: 'community', allocated_budget: 12000000, estimated_volume: 240, quality_score: 88, fraud_risk: 'low' },
      { channel_type: 'creator', allocated_budget: 10000000, estimated_volume: 200, quality_score: 85, fraud_risk: 'low' },
    ],
    start_date: '2024-04-15',
    end_date: '2024-07-15',
    created_at: '2024-04-10T11:00:00Z',
  },
  {
    id: 'prog_3',
    advertiser_id: 'adv_3',
    advertiser_name: 'XL Axiata',
    name: 'XL eSIM Purchase',
    brand_name: 'XL',
    industry: 'Telecommunications',
    description: 'Promote XL eSIM packages targeting tech-savvy users in urban areas.',
    objectives: ['purchase', 'app_install'],
    target_audience: {
      age: '18-35',
      gender: 'all',
      location: 'Jakarta, Medan, Surabaya',
      interest: 'Technology, Gaming, Streaming',
      device: 'Mobile',
      notes: 'Focus on digital-native users',
    },
    budget: 30000000,
    payout_model: 'CPA',
    payout_amount: 15000,
    advertiser_price: 20000,
    partner_payout: 3000,
    platform_profit: 17000,
    total_advertiser_cost: 30000000,
    total_partner_payout: 4500000,
    total_platform_profit: 25500000,
    target_volume: 2000,
    status: 'active',
    channels: [
      { channel_type: 'creator', allocated_budget: 15000000, estimated_volume: 1000, quality_score: 89, fraud_risk: 'low' },
      { channel_type: 'media', allocated_budget: 10000000, estimated_volume: 667, quality_score: 84, fraud_risk: 'low' },
      { channel_type: 'affiliate', allocated_budget: 5000000, estimated_volume: 333, quality_score: 80, fraud_risk: 'low' },
    ],
    start_date: '2024-05-01',
    end_date: '2024-08-31',
    created_at: '2024-04-25T12:00:00Z',
  },
  {
    id: 'prog_4',
    advertiser_id: 'adv_4',
    advertiser_name: 'Pegadaian',
    name: 'Pegadaian App Download + Registration',
    brand_name: 'Pegadaian',
    industry: 'Financial Services',
    description: 'Digital transformation initiative to acquire app users for Pegadaian digital services.',
    objectives: ['app_install', 'registration'],
    target_audience: {
      age: '25-50',
      gender: 'all',
      location: 'Nasional',
      interest: 'Gold, Loans, Investment',
      device: 'Mobile',
      notes: 'Target existing Pegadaian customers',
    },
    budget: 35000000,
    payout_model: 'CPA',
    payout_amount: 20000,
    advertiser_price: 25000,
    partner_payout: 5000,
    platform_profit: 20000,
    total_advertiser_cost: 25000000,
    total_partner_payout: 5000000,
    total_platform_profit: 20000000,
    target_volume: 1750,
    status: 'active',
    channels: [
      { channel_type: 'media', allocated_budget: 15000000, estimated_volume: 750, quality_score: 86, fraud_risk: 'low' },
      { channel_type: 'community', allocated_budget: 10000000, estimated_volume: 500, quality_score: 90, fraud_risk: 'low' },
      { channel_type: 'sales', allocated_budget: 6000000, estimated_volume: 300, quality_score: 82, fraud_risk: 'medium' },
      { channel_type: 'creator', allocated_budget: 4000000, estimated_volume: 200, quality_score: 84, fraud_risk: 'low' },
    ],
    start_date: '2024-04-20',
    end_date: '2024-07-20',
    created_at: '2024-04-15T13:00:00Z',
  },
  {
    id: 'prog_5',
    advertiser_id: 'adv_5',
    advertiser_name: 'AstraPay',
    name: 'AstraPay Review & Rating',
    brand_name: 'AstraPay',
    industry: 'Fintech',
    description: 'Increase app store ratings and reviews for AstraPay to improve visibility.',
    objectives: ['review_rating', 'app_install'],
    target_audience: {
      age: '20-40',
      gender: 'all',
      location: 'Nasional',
      interest: 'Digital Payment, E-Wallet',
      device: 'Mobile',
      notes: 'Target existing users for reviews',
    },
    budget: 20000000,
    payout_model: 'CPA',
    payout_amount: 10000,
    advertiser_price: 15000,
    partner_payout: 2500,
    platform_profit: 12500,
    total_advertiser_cost: 30000000,
    total_partner_payout: 5000000,
    total_platform_profit: 25000000,
    target_volume: 2000,
    status: 'active',
    channels: [
      { channel_type: 'creator', allocated_budget: 10000000, estimated_volume: 1000, quality_score: 88, fraud_risk: 'low' },
      { channel_type: 'mission', allocated_budget: 6000000, estimated_volume: 600, quality_score: 62, fraud_risk: 'high' },
      { channel_type: 'affiliate', allocated_budget: 4000000, estimated_volume: 400, quality_score: 78, fraud_risk: 'medium' },
    ],
    start_date: '2024-05-15',
    end_date: '2024-08-15',
    created_at: '2024-05-10T14:00:00Z',
  },
  {
    id: 'prog_6',
    advertiser_id: 'adv_6',
    advertiser_name: 'Bank Saqu',
    name: 'Bank Saqu Download + Registration',
    brand_name: 'Bank Saqu',
    industry: 'Banking',
    description: 'Launch campaign for Bank Saqu digital banking app targeting Gen Z and millennials.',
    objectives: ['app_install', 'registration'],
    target_audience: {
      age: '18-30',
      gender: 'all',
      location: 'Jakarta, Bandung, Surabaya',
      interest: 'Digital Banking, Savings',
      device: 'Mobile',
      notes: 'Focus on first-time bank account holders',
    },
    budget: 60000000,
    payout_model: 'CPA',
    payout_amount: 35000,
    advertiser_price: 40000,
    partner_payout: 8000,
    platform_profit: 32000,
    total_advertiser_cost: 20000000,
    total_partner_payout: 4000000,
    total_platform_profit: 16000000,
    target_volume: 1714,
    status: 'active',
    channels: [
      { channel_type: 'media', allocated_budget: 25000000, estimated_volume: 714, quality_score: 91, fraud_risk: 'low' },
      { channel_type: 'creator', allocated_budget: 20000000, estimated_volume: 571, quality_score: 93, fraud_risk: 'low' },
      { channel_type: 'affiliate', allocated_budget: 10000000, estimated_volume: 286, quality_score: 84, fraud_risk: 'low' },
      { channel_type: 'community', allocated_budget: 5000000, estimated_volume: 143, quality_score: 87, fraud_risk: 'low' },
    ],
    start_date: '2024-05-01',
    end_date: '2024-08-01',
    created_at: '2024-04-25T15:00:00Z',
  },
  {
    id: 'prog_7',
    advertiser_id: 'adv_7',
    advertiser_name: 'TMRW by UOB',
    name: 'TMRW App Registration',
    brand_name: 'TMRW',
    industry: 'Banking',
    description: 'Promote TMRW digital banking app targeting tech-savvy millennials in major cities.',
    objectives: ['registration', 'app_install'],
    target_audience: {
      age: '22-35',
      gender: 'all',
      location: 'Jakarta, Surabaya, Bali',
      interest: 'Digital Banking, Lifestyle',
      device: 'Mobile',
      notes: 'Target urban professionals',
    },
    budget: 45000000,
    payout_model: 'CPA',
    payout_amount: 40000,
    advertiser_price: 50000,
    partner_payout: 10000,
    platform_profit: 40000,
    total_advertiser_cost: 15000000,
    total_partner_payout: 3000000,
    total_platform_profit: 12000000,
    target_volume: 1125,
    status: 'active',
    channels: [
      { channel_type: 'creator', allocated_budget: 20000000, estimated_volume: 500, quality_score: 90, fraud_risk: 'low' },
      { channel_type: 'media', allocated_budget: 15000000, estimated_volume: 375, quality_score: 88, fraud_risk: 'low' },
      { channel_type: 'affiliate', allocated_budget: 10000000, estimated_volume: 250, quality_score: 82, fraud_risk: 'low' },
    ],
    start_date: '2024-05-10',
    end_date: '2024-08-10',
    created_at: '2024-05-05T16:00:00Z',
  },
  {
    id: 'prog_8',
    advertiser_id: 'adv_8',
    advertiser_name: 'IKEA Indonesia',
    name: 'IKEA Lead Form',
    brand_name: 'IKEA',
    industry: 'Retail',
    description: 'Generate home furnishing leads from interested customers in Jakarta area.',
    objectives: ['lead_form'],
    target_audience: {
      age: '25-45',
      gender: 'all',
      location: 'Jakarta, Tangerang',
      interest: 'Home Decor, Furniture',
      device: 'Mobile, Desktop',
      notes: 'Target new homeowners and renovators',
    },
    budget: 25000000,
    payout_model: 'CPL',
    payout_amount: 30000,
    advertiser_price: 35000,
    partner_payout: 7000,
    platform_profit: 28000,
    total_advertiser_cost: 35000000,
    total_partner_payout: 7000000,
    total_platform_profit: 28000000,
    target_volume: 833,
    status: 'active',
    channels: [
      { channel_type: 'media', allocated_budget: 12000000, estimated_volume: 400, quality_score: 89, fraud_risk: 'low' },
      { channel_type: 'creator', allocated_budget: 8000000, estimated_volume: 267, quality_score: 86, fraud_risk: 'low' },
      { channel_type: 'community', allocated_budget: 5000000, estimated_volume: 166, quality_score: 84, fraud_risk: 'low' },
    ],
    start_date: '2024-06-01',
    end_date: '2024-09-01',
    created_at: '2024-05-25T17:00:00Z',
  },
  {
    id: 'prog_9',
    advertiser_id: 'adv_9',
    advertiser_name: 'Pizza Hut Indonesia',
    name: 'Pizza Hut Lead Form',
    brand_name: 'Pizza Hut',
    industry: 'F&B',
    description: 'Generate delivery app sign-ups and catering leads for Pizza Hut Indonesia.',
    objectives: ['lead_form', 'app_install'],
    target_audience: {
      age: '18-40',
      gender: 'all',
      location: 'Nasional',
      interest: 'Food Delivery, Family Dining',
      device: 'Mobile',
      notes: 'Target families and young professionals',
    },
    budget: 18000000,
    payout_model: 'CPL',
    payout_amount: 15000,
    advertiser_price: 20000,
    partner_payout: 4000,
    platform_profit: 16000,
    total_advertiser_cost: 40000000,
    total_partner_payout: 8000000,
    total_platform_profit: 32000000,
    target_volume: 1200,
    status: 'active',
    channels: [
      { channel_type: 'creator', allocated_budget: 8000000, estimated_volume: 533, quality_score: 83, fraud_risk: 'low' },
      { channel_type: 'affiliate', allocated_budget: 6000000, estimated_volume: 400, quality_score: 78, fraud_risk: 'medium' },
      { channel_type: 'community', allocated_budget: 4000000, estimated_volume: 267, quality_score: 80, fraud_risk: 'low' },
    ],
    start_date: '2024-06-15',
    end_date: '2024-09-15',
    created_at: '2024-06-10T18:00:00Z',
  },
  {
    id: 'prog_10',
    advertiser_id: 'adv_10',
    advertiser_name: 'Yamaha Indonesia',
    name: 'Yamaha Lead Form',
    brand_name: 'Yamaha',
    industry: 'Automotive',
    description: 'Generate test ride bookings and showroom visit leads for Yamaha motorcycle buyers.',
    objectives: ['lead_form', 'event_attendance'],
    target_audience: {
      age: '18-45',
      gender: 'male',
      location: 'Nasional',
      interest: 'Motorcycle, Automotive',
      device: 'Mobile, Desktop',
      notes: 'Target first-time buyers and upgraders',
    },
    budget: 35000000,
    payout_model: 'CPL',
    payout_amount: 25000,
    advertiser_price: 30000,
    partner_payout: 6000,
    platform_profit: 24000,
    total_advertiser_cost: 45000000,
    total_partner_payout: 9000000,
    total_platform_profit: 36000000,
    target_volume: 1400,
    status: 'pending',
    channels: [
      { channel_type: 'media', allocated_budget: 15000000, estimated_volume: 600, quality_score: 87, fraud_risk: 'low' },
      { channel_type: 'creator', allocated_budget: 12000000, estimated_volume: 480, quality_score: 88, fraud_risk: 'low' },
      { channel_type: 'sales', allocated_budget: 8000000, estimated_volume: 320, quality_score: 75, fraud_risk: 'medium' },
    ],
    start_date: '2024-07-01',
    end_date: '2024-09-30',
    created_at: '2024-06-20T19:00:00Z',
  },
];

// Mock Media Inventory (100+ partners)
export const mockMediaInventory: MediaInventory[] = [
  // National News
  { id: 'media_1', partner_id: 'part_11', media_name: 'Kompas', category: 'national_news', region: 'Nasional', monthly_reach: 25000000, available_slots: 50, avg_conversion_rate: 3.2, quality_score: 92, status: 'active' },
  { id: 'media_2', partner_id: 'part_12', media_name: 'Tempo', category: 'national_news', region: 'Nasional', monthly_reach: 18000000, available_slots: 40, avg_conversion_rate: 3.5, quality_score: 91, status: 'active' },
  { id: 'media_3', partner_id: 'part_13', media_name: 'Detik News', category: 'national_news', region: 'Nasional', monthly_reach: 45000000, available_slots: 100, avg_conversion_rate: 2.8, quality_score: 88, status: 'active' },
  { id: 'media_4', partner_id: 'part_14', media_name: 'CNN Indonesia', category: 'national_news', region: 'Nasional', monthly_reach: 35000000, available_slots: 80, avg_conversion_rate: 3.1, quality_score: 90, status: 'active' },
  { id: 'media_5', partner_id: 'part_15', media_name: 'Tribun News', category: 'national_news', region: 'Nasional', monthly_reach: 30000000, available_slots: 75, avg_conversion_rate: 2.5, quality_score: 85, status: 'active' },
  // Finance Media
  { id: 'media_6', partner_id: 'part_16', media_name: 'Katadata', category: 'finance', region: 'Nasional', monthly_reach: 8500000, available_slots: 30, avg_conversion_rate: 4.8, quality_score: 95, status: 'active' },
  { id: 'media_7', partner_id: 'part_17', media_name: 'Kontan', category: 'finance', region: 'Nasional', monthly_reach: 5200000, available_slots: 25, avg_conversion_rate: 4.5, quality_score: 93, status: 'active' },
  { id: 'media_8', partner_id: 'part_18', media_name: 'Bloomberg Indonesia', category: 'finance', region: 'Nasional', monthly_reach: 3200000, available_slots: 20, avg_conversion_rate: 5.2, quality_score: 96, status: 'active' },
  { id: 'media_9', partner_id: 'part_19', media_name: 'CNBC Indonesia', category: 'finance', region: 'Nasional', monthly_reach: 6800000, available_slots: 35, avg_conversion_rate: 4.3, quality_score: 94, status: 'active' },
  // Lifestyle
  { id: 'media_10', partner_id: 'part_20', media_name: 'Femina', category: 'lifestyle', region: 'Nasional', monthly_reach: 4500000, available_slots: 25, avg_conversion_rate: 3.8, quality_score: 88, status: 'active' },
  { id: 'media_11', partner_id: 'part_21', media_name: 'Dewi', category: 'lifestyle', region: 'Nasional', monthly_reach: 3800000, available_slots: 20, avg_conversion_rate: 3.6, quality_score: 87, status: 'active' },
  { id: 'media_12', partner_id: 'part_22', media_name: 'Grazia Indonesia', category: 'lifestyle', region: 'Nasional', monthly_reach: 2200000, available_slots: 15, avg_conversion_rate: 4.1, quality_score: 89, status: 'active' },
  // Parenting
  { id: 'media_13', partner_id: 'part_23', media_name: 'Ayahbunda', category: 'parenting', region: 'Nasional', monthly_reach: 5800000, available_slots: 30, avg_conversion_rate: 4.2, quality_score: 90, status: 'active' },
  { id: 'media_14', partner_id: 'part_24', media_name: 'Nova', category: 'parenting', region: 'Nasional', monthly_reach: 4200000, available_slots: 25, avg_conversion_rate: 3.9, quality_score: 88, status: 'active' },
  // Automotive
  { id: 'media_15', partner_id: 'part_25', media_name: 'Otofriend', category: 'automotive', region: 'Nasional', monthly_reach: 3500000, available_slots: 20, avg_conversion_rate: 4.5, quality_score: 91, status: 'active' },
  { id: 'media_16', partner_id: 'part_26', media_name: 'Mobil123', category: 'automotive', region: 'Nasional', monthly_reach: 4200000, available_slots: 25, avg_conversion_rate: 4.3, quality_score: 90, status: 'active' },
  { id: 'media_17', partner_id: 'part_27', media_name: 'Motorplus', category: 'automotive', region: 'Nasional', monthly_reach: 6800000, available_slots: 40, avg_conversion_rate: 3.8, quality_score: 86, status: 'active' },
  // Tech
  { id: 'media_18', partner_id: 'part_28', media_name: 'Tekno Liputan6', category: 'tech', region: 'Nasional', monthly_reach: 15000000, available_slots: 50, avg_conversion_rate: 3.4, quality_score: 89, status: 'active' },
  { id: 'media_19', partner_id: 'part_29', media_name: 'Gadget 360', category: 'tech', region: 'Nasional', monthly_reach: 8500000, available_slots: 35, avg_conversion_rate: 3.7, quality_score: 87, status: 'active' },
  { id: 'media_20', partner_id: 'part_30', media_name: 'Technologue', category: 'tech', region: 'Nasional', monthly_reach: 3200000, available_slots: 20, avg_conversion_rate: 4.0, quality_score: 88, status: 'active' },
  // Muslim Family
  { id: 'media_21', partner_id: 'part_31', media_name: 'Republika', category: 'muslim_family', region: 'Nasional', monthly_reach: 12000000, available_slots: 60, avg_conversion_rate: 3.6, quality_score: 90, status: 'active' },
  { id: 'media_22', partner_id: 'part_32', media_name: 'Sinar', category: 'muslim_family', region: 'Nasional', monthly_reach: 8500000, available_slots: 45, avg_conversion_rate: 3.4, quality_score: 88, status: 'active' },
  { id: 'media_23', partner_id: 'part_33', media_name: 'Hidayah', category: 'muslim_family', region: 'Nasional', monthly_reach: 5200000, available_slots: 30, avg_conversion_rate: 3.8, quality_score: 89, status: 'active' },
  { id: 'media_24', partner_id: 'part_34', media_name: 'Kabar Islam', category: 'muslim_family', region: 'Nasional', monthly_reach: 3800000, available_slots: 25, avg_conversion_rate: 3.5, quality_score: 87, status: 'active' },
  // Entertainment
  { id: 'media_25', partner_id: 'part_35', media_name: 'VIVA', category: 'entertainment', region: 'Nasional', monthly_reach: 22000000, available_slots: 70, avg_conversion_rate: 2.6, quality_score: 82, status: 'active' },
  { id: 'media_26', partner_id: 'part_36', media_name: 'IDN Media', category: 'entertainment', region: 'Nasional', monthly_reach: 35000000, available_slots: 90, avg_conversion_rate: 2.9, quality_score: 84, status: 'active' },
  // Local News
  { id: 'media_27', partner_id: 'part_37', media_name: 'Jawa Pos', category: 'local_news', region: 'Jawa Timur', monthly_reach: 15000000, available_slots: 50, avg_conversion_rate: 3.2, quality_score: 88, status: 'active' },
  { id: 'media_28', partner_id: 'part_38', media_name: 'Pikiran Rakyat', category: 'local_news', region: 'Jawa Barat', monthly_reach: 8500000, available_slots: 40, avg_conversion_rate: 3.0, quality_score: 86, status: 'active' },
  { id: 'media_29', partner_id: 'part_39', media_name: 'Suara Merdeka', category: 'local_news', region: 'Jawa Tengah', monthly_reach: 5200000, available_slots: 30, avg_conversion_rate: 3.1, quality_score: 85, status: 'active' },
  { id: 'media_30', partner_id: 'part_40', media_name: 'Medan Pos', category: 'local_news', region: 'Sumatera Utara', monthly_reach: 3200000, available_slots: 25, avg_conversion_rate: 2.8, quality_score: 83, status: 'active' },
  // More media partners to reach 100+
  { id: 'media_31', partner_id: 'part_41', media_name: 'JakselNews', category: 'lifestyle', region: 'Jakarta Selatan', monthly_reach: 2500000, available_slots: 20, avg_conversion_rate: 4.2, quality_score: 91, status: 'active' },
  { id: 'media_32', partner_id: 'part_42', media_name: 'Jakarta Post', category: 'national_news', region: 'Nasional', monthly_reach: 4500000, available_slots: 25, avg_conversion_rate: 3.5, quality_score: 92, status: 'active' },
  { id: 'media_33', partner_id: 'part_43', media_name: 'Bisnis Indonesia', category: 'finance', region: 'Nasional', monthly_reach: 3800000, available_slots: 20, avg_conversion_rate: 4.6, quality_score: 94, status: 'active' },
  { id: 'media_34', partner_id: 'part_44', media_name: 'Investor Daily', category: 'finance', region: 'Nasional', monthly_reach: 2800000, available_slots: 15, avg_conversion_rate: 4.8, quality_score: 95, status: 'active' },
  { id: 'media_35', partner_id: 'part_45', media_name: 'Seputar Indonesia', category: 'national_news', region: 'Nasional', monthly_reach: 28000000, available_slots: 65, avg_conversion_rate: 2.7, quality_score: 85, status: 'active' },
];

// Generate more media partners to reach 100+
const categories = ['national_news', 'local_news', 'finance', 'lifestyle', 'parenting', 'automotive', 'education', 'tech', 'muslim_family', 'entertainment'] as const;
const regions = ['Jakarta', 'Surabaya', 'Bandung', 'Medan', 'Makassar', 'Semarang', 'Palembang', 'Yogyakarta', 'Denpasar', 'Malang'];

for (let i = 36; i <= 120; i++) {
  const category = categories[i % categories.length];
  const region = regions[i % regions.length];
  const mediaNumber = i - 35;

  mockMediaInventory.push({
    id: `media_${i}`,
    partner_id: `part_${40 + i}`,
    media_name: `${region} ${category.charAt(0).toUpperCase() + category.slice(1).replace('_', ' ')} ${mediaNumber}`,
    category,
    region: i % 3 === 0 ? 'Nasional' : region,
    monthly_reach: Math.floor(Math.random() * 5000000) + 500000,
    available_slots: Math.floor(Math.random() * 30) + 10,
    avg_conversion_rate: Math.random() * 2 + 2.5,
    quality_score: Math.floor(Math.random() * 15) + 80,
    status: i % 10 === 0 ? 'inactive' : 'active',
  });
}

// Mock Conversions
export const mockConversions: Conversion[] = [
  {
    id: 'conv_1',
    program_id: 'prog_1',
    program_name: 'Tunaiku Download + Registration',
    partner_id: 'part_1',
    partner_name: 'JakselNews Media Network',
    channel_type: 'media',
    conversion_type: 'registration',
    user_identifier: 'user_12345',
    ip_address: '192.168.1.100',
    device_id: 'device_abc123',
    fingerprint: 'fp_abc123xyz',
    advertiser_price: 30000,
    partner_payout: 25000,
    platform_profit: 5000,
    payout_amount: 25000,
    status: 'valid',
    quality_score: 92,
    fraud_signals: [],
    created_at: '2024-06-01T10:30:00Z',
  },
  {
    id: 'conv_2',
    program_id: 'prog_1',
    program_name: 'Tunaiku Download + Registration',
    partner_id: 'part_2',
    partner_name: 'Finance Creator Jakarta',
    channel_type: 'creator',
    conversion_type: 'registration',
    user_identifier: 'user_12346',
    ip_address: '192.168.1.101',
    device_id: 'device_def456',
    fingerprint: 'fp_def456uvw',
    advertiser_price: 30000,
    partner_payout: 25000,
    platform_profit: 5000,
    payout_amount: 25000,
    status: 'valid',
    quality_score: 95,
    fraud_signals: [],
    created_at: '2024-06-01T11:45:00Z',
  },
  {
    id: 'conv_3',
    program_id: 'prog_2',
    program_name: 'PRULady Lead Form',
    partner_id: 'part_4',
    partner_name: 'Parenting Community Indonesia',
    channel_type: 'community',
    conversion_type: 'lead_form',
    user_identifier: 'user_12347',
    ip_address: '192.168.1.102',
    device_id: 'device_ghi789',
    fingerprint: 'fp_ghi789rst',
    advertiser_price: 50000,
    partner_payout: 50000,
    platform_profit: 0,
    payout_amount: 50000,
    status: 'pending',
    quality_score: 78,
    fraud_signals: ['suspicious_velocity'],
    created_at: '2024-06-01T12:00:00Z',
  },
  {
    id: 'conv_4',
    program_id: 'prog_3',
    program_name: 'XL eSIM Purchase',
    partner_id: 'part_2',
    partner_name: 'Finance Creator Jakarta',
    channel_type: 'creator',
    conversion_type: 'purchase',
    user_identifier: 'user_12348',
    ip_address: '192.168.1.103',
    device_id: 'device_jkl012',
    fingerprint: 'fp_jkl012nop',
    advertiser_price: 20000,
    partner_payout: 15000,
    platform_profit: 5000,
    payout_amount: 15000,
    status: 'valid',
    quality_score: 88,
    fraud_signals: [],
    created_at: '2024-06-01T14:30:00Z',
  },
  {
    id: 'conv_5',
    program_id: 'prog_1',
    program_name: 'Tunaiku Download + Registration',
    partner_id: 'part_7',
    partner_name: 'Mission User Network',
    channel_type: 'mission',
    conversion_type: 'registration',
    user_identifier: 'user_12349',
    ip_address: '192.168.1.104',
    device_id: 'device_mno345',
    fingerprint: 'fp_mno345lmn',
    advertiser_price: 30000,
    partner_payout: 25000,
    platform_profit: 5000,
    payout_amount: 25000,
    status: 'fraud',
    quality_score: 35,
    fraud_signals: ['duplicate_ip', 'duplicate_device', 'suspicious_velocity'],
    created_at: '2024-06-01T15:00:00Z',
  },
  {
    id: 'conv_6',
    program_id: 'prog_6',
    program_name: 'Bank Saqu Download + Registration',
    partner_id: 'part_1',
    partner_name: 'JakselNews Media Network',
    channel_type: 'media',
    conversion_type: 'registration',
    user_identifier: 'user_12350',
    ip_address: '192.168.1.105',
    device_id: 'device_pqr678',
    fingerprint: 'fp_pqr678ijk',
    advertiser_price: 40000,
    partner_payout: 35000,
    platform_profit: 5000,
    payout_amount: 35000,
    status: 'valid',
    quality_score: 94,
    fraud_signals: [],
    created_at: '2024-06-02T09:00:00Z',
  },
  {
    id: 'conv_7',
    program_id: 'prog_4',
    program_name: 'Pegadaian App Download + Registration',
    partner_id: 'part_4',
    partner_name: 'Parenting Community Indonesia',
    channel_type: 'community',
    conversion_type: 'registration',
    user_identifier: 'user_12351',
    ip_address: '192.168.1.106',
    device_id: 'device_stu901',
    fingerprint: 'fp_stu901ghi',
    advertiser_price: 25000,
    partner_payout: 20000,
    platform_profit: 5000,
    payout_amount: 20000,
    status: 'valid',
    quality_score: 90,
    fraud_signals: [],
    created_at: '2024-06-02T10:15:00Z',
  },
  {
    id: 'conv_8',
    program_id: 'prog_7',
    program_name: 'TMRW App Registration',
    partner_id: 'part_2',
    partner_name: 'Finance Creator Jakarta',
    channel_type: 'creator',
    conversion_type: 'registration',
    user_identifier: 'user_12352',
    ip_address: '192.168.1.107',
    device_id: 'device_vwx234',
    fingerprint: 'fp_vwx234def',
    advertiser_price: 50000,
    partner_payout: 40000,
    platform_profit: 10000,
    payout_amount: 40000,
    status: 'rejected',
    quality_score: 45,
    fraud_signals: ['invalid_email', 'low_engagement'],
    fraud_reason: 'Invalid email domain and low engagement detected',
    created_at: '2024-06-02T11:30:00Z',
  },
  {
    id: 'conv_9',
    program_id: 'prog_5',
    program_name: 'AstraPay Review & Rating',
    partner_id: 'part_7',
    partner_name: 'Mission User Network',
    channel_type: 'mission',
    conversion_type: 'review_rating',
    user_identifier: 'user_12353',
    ip_address: '192.168.1.108',
    device_id: 'device_yza567',
    fingerprint: 'fp_yza567abc',
    advertiser_price: 15000,
    partner_payout: 10000,
    platform_profit: 5000,
    payout_amount: 10000,
    status: 'fraud',
    quality_score: 28,
    fraud_signals: ['duplicate_device', 'emulator_suspected', 'proxy_vpn'],
    created_at: '2024-06-02T12:45:00Z',
  },
  {
    id: 'conv_10',
    program_id: 'prog_8',
    program_name: 'IKEA Lead Form',
    partner_id: 'part_3',
    partner_name: 'Local Media Bandung',
    channel_type: 'media',
    conversion_type: 'lead_form',
    user_identifier: 'user_12354',
    ip_address: '192.168.1.109',
    device_id: 'device_bcd890',
    fingerprint: 'fp_bcd890fgh',
    advertiser_price: 35000,
    partner_payout: 30000,
    platform_profit: 5000,
    payout_amount: 30000,
    status: 'valid',
    quality_score: 89,
    fraud_signals: [],
    created_at: '2024-06-02T14:00:00Z',
  },
];

// Mock Payouts
export const mockPayouts: Payout[] = [
  {
    id: 'payout_1',
    partner_id: 'part_1',
    partner_name: 'JakselNews Media Network',
    amount: 5250000,
    status: 'paid',
    payment_method: 'bank_transfer',
    bank_account: 'BCA 1234567890',
    approved_conversions: 150,
    paid_at: '2024-06-01T00:00:00Z',
    created_at: '2024-05-25T10:00:00Z',
  },
  {
    id: 'payout_2',
    partner_id: 'part_2',
    partner_name: 'Finance Creator Jakarta',
    amount: 3500000,
    status: 'paid',
    payment_method: 'bank_transfer',
    bank_account: 'Mandiri 9876543210',
    approved_conversions: 140,
    paid_at: '2024-06-01T00:00:00Z',
    created_at: '2024-05-25T11:00:00Z',
  },
  {
    id: 'payout_3',
    partner_id: 'part_4',
    partner_name: 'Parenting Community Indonesia',
    amount: 2800000,
    status: 'processing',
    payment_method: 'gopay',
    approved_conversions: 56,
    created_at: '2024-06-02T10:00:00Z',
  },
  {
    id: 'payout_4',
    partner_id: 'part_6',
    partner_name: 'Affiliate Finance Partner',
    amount: 4200000,
    status: 'pending',
    payment_method: 'bank_transfer',
    bank_account: 'BNI 5555666677',
    approved_conversions: 168,
    created_at: '2024-06-03T09:00:00Z',
  },
  {
    id: 'payout_5',
    partner_id: 'part_3',
    partner_name: 'Local Media Bandung',
    amount: 1850000,
    status: 'paid',
    payment_method: 'bank_transfer',
    bank_account: 'BTPN 1122334455',
    approved_conversions: 74,
    paid_at: '2024-05-15T00:00:00Z',
    created_at: '2024-05-10T08:00:00Z',
  },
];

// Dashboard Data
export const mockAdvertiserDashboard: AdvertiserDashboard = {
  active_programs: 8,
  total_conversions: 4521,
  total_advertiser_spend: 124327500,
  average_cpa: 27500,
  fraud_risk: 'medium',
  top_partner_type: 'creator',
  recent_programs: mockPrograms.slice(0, 5),
  ai_recommendation: 'Finance creators and media partners are producing higher registration quality than mission traffic. Consider shifting 20% allocation to media and creator channels.',
};

export const mockPartnerDashboard: PartnerDashboard = {
  active_programs: 12,
  total_conversions: 740,
  total_earnings: 18500000,
  pending_payout: 3500000,
  paid_out: 15000000,
  valid_conversions: 740,
  fraud_rate: 2.5,
  total_reach: 3350000,
  recent_programs: mockPrograms.slice(0, 4),
};

export const mockAdminDashboard: AdminDashboard = {
  active_advertisers: 42,
  active_partners: 156,
  active_programs: 67,
  total_conversions: 89456,
  valid_conversions: 78234,
  rejected_conversions: 5621,
  fraud_conversions: 5601,
  total_payouts: 1250000000,
  platform_revenue: 187500000,
  total_advertiser_revenue: 250000000,
  total_partner_payout: 125000000,
  total_platform_profit: 62500000,
  pending_payouts: 15600000,
  fraud_alerts: 23,
};

// Helper functions
export function formatCurrency(amount: number): string {
  return new Intl.NumberFormat('id-ID', {
    style: 'currency',
    currency: 'IDR',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(amount);
}

export function formatNumber(num: number): string {
  return new Intl.NumberFormat('id-ID').format(num);
}

export function formatDate(dateString: string): string {
  return new Intl.DateTimeFormat('id-ID', {
    day: 'numeric',
    month: 'short',
    year: 'numeric',
  }).format(new Date(dateString));
}

export function formatDateTime(dateString: string): string {
  return new Intl.DateTimeFormat('id-ID', {
    day: 'numeric',
    month: 'short',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  }).format(new Date(dateString));
}
